//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppKurierska
{
    using System;
    using System.Collections.Generic;
    
    public partial class przeplywy
    {
        public int przesylka_id { get; set; }
        public int oddzial_id { get; set; }
        public int opis_id { get; set; }
        public System.DateTime data { get; set; }
    
        public virtual oddzialy oddzialy { get; set; }
        public virtual opisy opisy { get; set; }
        public virtual przesylki przesylki { get; set; }
    }
}
