//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppKurierska
{
    using System;
    using System.Collections.Generic;
    
    public partial class reklamacje
    {
        public int reklamacja_id { get; set; }
        public int klient_id { get; set; }
        public int przesylka_id { get; set; }
        public System.DateTime data_zlozenia { get; set; }
        public Nullable<System.DateTime> data_rozpatrzenia { get; set; }
        public string status { get; set; }
    
        public virtual klienci klienci { get; set; }
        public virtual przesylki przesylki { get; set; }
    }
}
