//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppKurierska
{
    using System;
    using System.Collections.Generic;
    
    public partial class samochody
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public samochody()
        {
            this.zamowienia = new HashSet<zamowienia>();
        }
    
        public int samochod_id { get; set; }
        public string numer_rejestracyjny { get; set; }
        public string pojemnosc { get; set; }
        public string ladownosc { get; set; }
        public Nullable<int> kurier_id { get; set; }
    
        public virtual kurierzy kurierzy { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<zamowienia> zamowienia { get; set; }
    }
}
