//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppKurierska
{
    using System;
    using System.Collections.Generic;
    
    public partial class zamowienia
    {
        public int przesylka_id { get; set; }
        public int nadawca_id { get; set; }
        public int nadawca_adres_id { get; set; }
        public int odbiorca_id { get; set; }
        public int odbiorca_adres_id { get; set; }
        public Nullable<int> kurier_id { get; set; }
        public Nullable<int> samochod_id { get; set; }
        public Nullable<System.DateTime> data { get; set; }
        public string zakonczona { get; set; }
    
        public virtual adresy adresy { get; set; }
        public virtual adresy adresy1 { get; set; }
        public virtual klienci klienci { get; set; }
        public virtual klienci klienci1 { get; set; }
        public virtual kurierzy kurierzy { get; set; }
        public virtual przesylki przesylki { get; set; }
        public virtual samochody samochody { get; set; }
    }
}
