// <auto-generated />
namespace Kurier.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class dodanienulowalnychdatdopaczki : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(dodanienulowalnychdatdopaczki));
        
        string IMigrationMetadata.Id
        {
            get { return "201612062309366_dodanie nulowalnych dat do paczki"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
