// <auto-generated />
namespace Kurier.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Dodaniekurieradostatusu : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Dodaniekurieradostatusu));
        
        string IMigrationMetadata.Id
        {
            get { return "201611152253243_Dodanie kuriera do statusu"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
