// <auto-generated />
namespace Kurier.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class migration3 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(migration3));
        
        string IMigrationMetadata.Id
        {
            get { return "201611162126157_migration3"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
